"""add bon percentage and fixed bon fields to client model

Revision ID: c7a3c49bea62
Revises: 4a3d5e1cdbc4
Create Date: 2025-07-10 04:34:03.230867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7a3c49bea62'
down_revision = '4a3d5e1cdbc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bon_percentage', sa.Float(), nullable=False, server_default='30.0'))
        batch_op.add_column(sa.Column('use_fixed_bon', sa.Boolean(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('use_fixed_bon')
        batch_op.drop_column('bon_percentage')

    # ### end Alembic commands ###
